import os
import re
import time
import hashlib
import logging
import threading
import requests
import numpy as np
from contextlib import asynccontextmanager
from typing import List, Literal, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, field_validator
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from supabase import create_client, Client
from youtube_transcript_api import (
    YouTubeTranscriptApi,
    TranscriptsDisabled,
    NoTranscriptFound,
)

# ---- Logging ----
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)

# ---- Conditional Imports ----
try:
    from youtube_transcript_api import VideoUnavailable
    HAS_VIDEO_UNAVAILABLE = True
except ImportError:
    HAS_VIDEO_UNAVAILABLE = False

try:
    from groq import Groq
    GROQ_AVAILABLE = True
except ImportError:
    GROQ_AVAILABLE = False
    logger.warning("groq not installed")

try:
    from duckduckgo_search import DDGS
    DDGS_AVAILABLE = True
except ImportError:
    DDGS_AVAILABLE = False

# ---- Environment ----
load_dotenv()
SUPABASE_URL    = os.getenv("SUPABASE_URL")
SUPABASE_KEY    = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
GROQ_API_KEY    = os.getenv("GROQ_API_KEY")
HF_TOKEN        = os.getenv("HF_TOKEN")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
ALLOWED_ORIGINS = os.getenv(
    "ALLOWED_ORIGINS",
    "https://barprepfront.netlify.app,http://localhost:5173,http://localhost:3000"
).split(",")

if not all([SUPABASE_URL, SUPABASE_KEY]):
    raise ValueError("Missing: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY")

if not GROQ_API_KEY:
    logger.warning("GROQ_API_KEY not set")

if not YOUTUBE_API_KEY:
    logger.warning("YOUTUBE_API_KEY not set - video metadata will use fallback")

# ---- Clients ----
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

groq_client = None
if GROQ_API_KEY and GROQ_AVAILABLE:
    groq_client = Groq(api_key=GROQ_API_KEY)
    logger.info("Groq client initialized")

# ---- Constants ----
HF_EMBED_URL      = "https://api-inference.huggingface.co/pipeline/feature-extraction/sentence-transformers/all-MiniLM-L6-v2"
POLLINATIONS_URL  = "https://text.pollinations.ai"
MAX_CONTENT_BYTES = 5 * 1024 * 1024
MAX_CHUNKS        = 200
CHUNK_SIZE        = 1000
CHUNK_OVERLAP     = 200
RAG_THRESHOLD     = 0.5
RAG_MATCH_COUNT   = 4
GROQ_MODEL        = "llama-3.1-8b-instant"
EMBEDDING_DIM     = 384

AD_PATTERNS = [
    r'pollinations\.ai[^\n]*',
    r'generated by pollinations[^\n]*',
    r'powered by pollinations[^\n]*',
    r'https?://[^\s]*pollinations[^\s]*',
    r'image by[^\n]*',
    r'via pollinations[^\n]*',
    r'\[.*?pollinations.*?\]',
    r'🌸[^\n]*',
]

# ---- Lifespan ----
@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("BarPrep AI Backend starting...")
    logger.info(f"CORS Origins: {ALLOWED_ORIGINS}")
    logger.info(f"Groq Ready: {groq_client is not None}")
    logger.info(f"HF Token Set: {bool(HF_TOKEN)}")
    logger.info(f"YouTube API: {bool(YOUTUBE_API_KEY)}")
    logger.info(f"DDG Available: {DDGS_AVAILABLE}")
    yield
    logger.info("BarPrep AI Backend shutting down.")

# ---- App ----
app = FastAPI(title="BarPrep AI Backend", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
    expose_headers=["*"],
    max_age=3600,
)

# ---- Schemas ----
class IngestRequest(BaseModel):
    url: str

    @field_validator("url")
    @classmethod
    def url_must_be_valid(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("URL cannot be empty")
        if not v.startswith(("http://", "https://")):
            raise ValueError("URL must start with http:// or https://")
        return v.strip()


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str

    @field_validator("content")
    @classmethod
    def content_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Content cannot be empty")
        if len(v) > 4000:
            raise ValueError("Content too long (max 4000 chars)")
        return v.strip()


class ChatRequest(BaseModel):
    message: str
    history: List[ChatMessage] = []

    @field_validator("message")
    @classmethod
    def message_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Message cannot be empty")
        if len(v) > 2000:
            raise ValueError("Message too long (max 2000 chars)")
        return v.strip()

    @field_validator("history")
    @classmethod
    def history_not_too_long(cls, v: List[ChatMessage]) -> List[ChatMessage]:
        if len(v) > 20:
            raise ValueError("History too long (max 20 messages)")
        return v


class VideoRequest(BaseModel):
    url: str
    topic: str = "Bar Exam"
    order_index: int = 0

    @field_validator("url")
    @classmethod
    def url_must_be_valid(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("URL cannot be empty")
        if not v.startswith(("http://", "https://")):
            raise ValueError("URL must start with http:// or https://")
        return v.strip()


# ---- Helpers ----

def clean_llm_response(text: str) -> str:
    if not text:
        return ""
    cleaned = text
    for pattern in AD_PATTERNS:
        cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'\n{3,}', '\n\n', cleaned)
    return cleaned.strip()


def sanitize_for_prompt(text: str) -> str:
    text = text.replace("===", "---")
    return text[:8000]


def generate_hash_embedding(text: str) -> List[float]:
    embedding = np.zeros(EMBEDDING_DIM)
    for seed in range(EMBEDDING_DIM):
        hash_input = f"{seed}:{text}".encode("utf-8")
        hash_val = int(hashlib.md5(hash_input).hexdigest(), 16)
        embedding[seed] = (hash_val % 10000) / 10000.0 - 0.5
    norm = np.linalg.norm(embedding)
    if norm > 0:
        embedding = embedding / norm
    return embedding.tolist()


def get_embeddings_batch(texts: List[str]) -> List[List[float]]:
    clean_texts = [t.replace("\n", " ").strip() for t in texts]
    try:
        headers = {"Authorization": f"Bearer {HF_TOKEN}"} if HF_TOKEN else {}
        response = requests.post(
            HF_EMBED_URL,
            headers=headers,
            json={
                "inputs": clean_texts,
                "options": {"wait_for_model": True}
            },
            timeout=15
        )
        if response.status_code == 200:
            result = response.json()
            if isinstance(result, list) and len(result) > 0:
                logger.info("Embeddings via HuggingFace")
                return result
    except Exception as e:
        logger.warning(f"HuggingFace unavailable: {e}")

    logger.info("Using local hash embeddings")
    return [generate_hash_embedding(text) for text in clean_texts]


def split_text(
    text: str,
    chunk_size: int = CHUNK_SIZE,
    overlap: int = CHUNK_OVERLAP
) -> List[str]:
    if not text or not text.strip():
        return []
    if overlap >= chunk_size:
        raise ValueError("Overlap must be less than chunk_size")
    chunks, start, step = [], 0, chunk_size - overlap
    while start < len(text):
        chunks.append(text[start:start + chunk_size])
        start += step
    return chunks


# ---- Video Processing Helpers ----

def get_video_metadata(video_id: str) -> dict:
    """Get video info via YouTube Data API v3"""
    fallback = {
        "title":       f"YouTube Video {video_id}",
        "description": "",
        "thumbnail":   f"https://img.youtube.com/vi/{video_id}/maxresdefault.jpg",
        "channel":     ""
    }

    if not YOUTUBE_API_KEY:
        logger.warning("No YOUTUBE_API_KEY - using fallback metadata")
        return fallback

    try:
        url = (
            f"https://www.googleapis.com/youtube/v3/videos"
            f"?id={video_id}"
            f"&key={YOUTUBE_API_KEY}"
            f"&part=snippet"
        )
        res = requests.get(url, timeout=10)

        if not res.ok:
            logger.warning(f"YouTube API returned {res.status_code}")
            return fallback

        data = res.json()
        if not data.get("items"):
            logger.warning("Video not found in YouTube API")
            return fallback

        snippet    = data["items"][0]["snippet"]
        thumbnails = snippet.get("thumbnails", {})
        thumbnail  = (
            thumbnails.get("maxres",   {}).get("url") or
            thumbnails.get("standard", {}).get("url") or
            thumbnails.get("high",     {}).get("url") or
            fallback["thumbnail"]
        )

        logger.info(f"Got video metadata: {snippet['title']}")
        return {
            "title":       snippet.get("title",        fallback["title"]),
            "description": snippet.get("description",  "")[:1000],
            "thumbnail":   thumbnail,
            "channel":     snippet.get("channelTitle", "")
        }

    except Exception as e:
        logger.error(f"YouTube API metadata failed: {e}")
        return fallback


def get_transcript_with_timeout(
    video_id: str,
    timeout_seconds: int = 10
) -> Optional[str]:
    """
    Fetch transcript using thread with hard timeout.
    Works safely in FastAPI worker threads.
    Returns None if blocked or timed out.
    """
    result_container = {"transcript": None, "error": None}

    def fetch():
        try:
            transcript_list = YouTubeTranscriptApi.get_transcript(
                video_id,
                languages=["en", "en-US", "en-GB"]
            )
            text = " ".join(
                entry["text"] for entry in transcript_list
            )
            result_container["transcript"] = text
            logger.info(f"Transcript fetched: {len(text)} chars")
        except Exception as e:
            result_container["error"] = str(e)
            logger.warning(f"Transcript fetch error: {e}")

    thread = threading.Thread(target=fetch, daemon=True)
    thread.start()
    thread.join(timeout=timeout_seconds)

    if thread.is_alive():
        logger.warning(
            f"Transcript timed out after {timeout_seconds}s - using fallback"
        )
        return None

    return result_container.get("transcript")


def generate_course_content_groq(
    text: str,
    title: str,
    topic: str
) -> dict:
    """Generate AI summary and outline using Groq"""
    fallback = {
        "summary": (
            f"This lecture covers essential {topic} concepts "
            f"for the bar exam. Students will learn key legal "
            f"principles rules and their applications in exam scenarios."
        ),
        "outline": (
            f"• Core {topic} legal principles\n"
            f"• Key rules and standards\n"
            f"• Important cases and holdings\n"
            f"• Bar exam applications\n"
            f"• Practice tips"
        )
    }

    if not groq_client:
        return fallback

    try:
        prompt = (
            f"Topic: {topic}\n"
            f"Video: {title}\n"
            f"Content: {text[:6000]}\n\n"
            f"Format EXACTLY:\n\n"
            f"SUMMARY:\n"
            f"[3-4 sentences about what bar exam students will learn]\n\n"
            f"OUTLINE:\n"
            f"• [Key concept 1]\n"
            f"• [Key concept 2]\n"
            f"• [Key concept 3]\n"
            f"• [Key concept 4]\n"
            f"• [Key concept 5]"
        )

        response = groq_client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a bar exam course creator. "
                        "Create structured educational content. "
                        "Be concise and focused on bar exam relevance."
                    )
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            model=GROQ_MODEL,
            max_tokens=500,
            temperature=0.5
        )

        content = response.choices[0].message.content

        summary_match = re.search(
            r'SUMMARY:\n([\s\S]+?)(?=\n\nOUTLINE:)', content
        )
        outline_match = re.search(
            r'OUTLINE:\n([\s\S]+?)$', content
        )

        return {
            "summary": (
                summary_match.group(1).strip()
                if summary_match else fallback["summary"]
            ),
            "outline": (
                outline_match.group(1).strip()
                if outline_match else fallback["outline"]
            )
        }

    except Exception as e:
        logger.error(f"Groq course generation failed: {e}")
        return fallback


# ---- Endpoints ----

@app.get("/")
def home():
    return {"status": "healthy", "service": "BarPrep AI Engine"}


@app.get("/api/health")
def health_check():
    return {
        "status":              "healthy",
        "groq_available":      groq_client is not None,
        "hf_token_set":        bool(HF_TOKEN),
        "supabase_connected":  bool(supabase),
        "youtube_api":         bool(YOUTUBE_API_KEY),
        "web_search":          DDGS_AVAILABLE,
    }


@app.post("/api/ingest/url")
def ingest_url(data: IngestRequest):
    """Scrapes a webpage and ingests into Supabase"""
    url = data.url
    try:
        res = requests.get(
            url,
            headers={"User-Agent": "Mozilla/5.0"},
            timeout=10,
            stream=True
        )
        if res.status_code != 200:
            raise HTTPException(
                status_code=400,
                detail=f"Page returned status {res.status_code}"
            )
        content = b""
        for chunk in res.iter_content(chunk_size=8192):
            content += chunk
            if len(content) > MAX_CONTENT_BYTES:
                raise HTTPException(
                    status_code=400,
                    detail=f"Page too large (max {MAX_CONTENT_BYTES // (1024*1024)}MB)"
                )
        soup = BeautifulSoup(content, "html.parser")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Could not reach URL: {e}")

    for tag in soup(["script", "style"]):
        tag.extract()

    title = (
        soup.title.string.strip()[:200]
        if soup.title and soup.title.string
        else "Untitled Page"
    )

    clean_text = "\n".join(
        line.strip() for line in soup.get_text().splitlines() if line.strip()
    )

    chunks = split_text(clean_text)
    if not chunks:
        return {"message": "Page contained no readable text."}

    if len(chunks) > MAX_CHUNKS:
        chunks = chunks[:MAX_CHUNKS]
        logger.warning(f"Truncated to {MAX_CHUNKS} chunks")

    try:
        embeddings = get_embeddings_batch(chunks)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Embedding failed: {e}")

    rows = [{
        "content":  chunk,
        "metadata": {
            "source":      url,
            "title":       title,
            "type":        "webpage",
            "chunk_index": i
        },
        "embedding": embeddings[i]
    } for i, chunk in enumerate(chunks)]

    try:
        supabase.table("documents").insert(rows).execute()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"DB insert failed: {e}")

    logger.info(f"Ingested {len(chunks)} chunks from '{title}'")
    return {
        "message": f"Successfully ingested {len(chunks)} chunks from '{title}'"
    }


@app.post("/api/ingest/youtube")
def ingest_youtube(data: IngestRequest):
    """Transcribes YouTube video and ingests into Supabase"""
    match = re.search(r"(?:v=|\/)([a-zA-Z0-9_-]{11})", data.url)
    if not match:
        raise HTTPException(status_code=400, detail="Invalid YouTube URL.")
    video_id = match.group(1)

    transcript_list = None
    last_error      = None

    for attempt in range(3):
        try:
            transcript_list = YouTubeTranscriptApi.get_transcript(video_id)
            break
        except TranscriptsDisabled:
            raise HTTPException(
                status_code=400,
                detail="Transcripts disabled for this video."
            )
        except NoTranscriptFound:
            raise HTTPException(
                status_code=404,
                detail="No transcript found for this video."
            )
        except Exception as e:
            last_error = e
            error_str  = str(e).lower()
            if "429" in str(e) or "too many requests" in error_str:
                wait_time = (attempt + 1) * 5
                logger.warning(f"YouTube rate limit. Waiting {wait_time}s...")
                time.sleep(wait_time)
                continue
            if HAS_VIDEO_UNAVAILABLE and isinstance(e, VideoUnavailable):
                raise HTTPException(
                    status_code=404,
                    detail="Video unavailable or private."
                )
            if any(k in error_str for k in ["unavailable", "private"]):
                raise HTTPException(
                    status_code=404,
                    detail="Video unavailable or private."
                )
            raise HTTPException(
                status_code=500,
                detail=f"Transcript error: {e}"
            )

    if transcript_list is None:
        raise HTTPException(
            status_code=429,
            detail="YouTube rate limiting. Please wait 5 minutes and retry."
        )

    full_transcript = " ".join(e["text"] for e in transcript_list)

    try:
        supabase.table("youtube_videos").upsert({
            "video_id":   video_id,
            "title":      f"YouTube Lecture: {video_id}",
            "transcript": full_transcript
        }).execute()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"DB upsert failed: {e}")

    chunks = split_text(full_transcript)
    if not chunks:
        return {"message": f"Video {video_id} had no usable transcript text."}

    if len(chunks) > MAX_CHUNKS:
        chunks = chunks[:MAX_CHUNKS]

    try:
        embeddings = get_embeddings_batch(chunks)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Embedding failed: {e}")

    rows = [{
        "content":  chunk,
        "metadata": {
            "source":      f"https://youtube.com/watch?v={video_id}",
            "video_id":    video_id,
            "type":        "youtube_transcript",
            "chunk_index": i
        },
        "embedding": embeddings[i]
    } for i, chunk in enumerate(chunks)]

    try:
        supabase.table("documents").insert(rows).execute()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"DB insert failed: {e}")

    logger.info(f"Processed video {video_id} into {len(chunks)} chunks")
    return {
        "message": f"Processed video {video_id} into {len(chunks)} chunks."
    }


@app.post("/api/process-video")
def process_video(data: VideoRequest):
    """
    Full video processing pipeline:
    1. Get metadata via YouTube Data API v3
    2. Try transcript with 10s thread timeout
    3. Fallback to description if blocked
    4. Generate AI course content via Groq
    5. Save module to Supabase
    6. Embed for RAG search
    """
    match = re.search(r"(?:v=|\/)([a-zA-Z0-9_-]{11})", data.url)
    if not match:
        raise HTTPException(
            status_code=400,
            detail="Invalid YouTube URL"
        )

    video_id = match.group(1)
    logger.info(f"=== Processing {video_id} | {data.topic} ===")

    # Step 1: Get metadata via YouTube Data API v3
    meta = get_video_metadata(video_id)
    logger.info(f"Title: {meta['title']}")

    # Step 2: Try transcript with thread timeout
    logger.info("Attempting transcript (10s timeout)...")
    transcript = get_transcript_with_timeout(video_id, timeout_seconds=10)

    # Step 3: Decide text source for AI
    if transcript and len(transcript) > 200:
        text_for_ai = transcript
        source_type = "transcript"
        logger.info(f"Using transcript: {len(transcript)} chars")

    elif meta["description"] and len(meta["description"]) > 100:
        text_for_ai = meta["description"]
        source_type = "description"
        logger.warning("Transcript blocked. Using video description.")

    else:
        text_for_ai = (
            f"Bar exam lecture about {data.topic}. "
            f"Video: {meta['title']}. "
            f"This covers key {data.topic} concepts for the bar exam."
        )
        source_type = "title_only"
        logger.warning("Using title only as last resort")

    logger.info(f"Source: {source_type} | Length: {len(text_for_ai)}")

    # Step 4: Generate AI course content
    logger.info("Generating course content...")
    content = generate_course_content_groq(
        text_for_ai,
        meta["title"],
        data.topic
    )

    # Step 5: Save to Supabase
    logger.info("Saving module to Supabase...")
    try:
        module_result = supabase.table("course_modules").insert({
            "title":         meta["title"],
            "description":   content["summary"],
            "topic":         data.topic,
            "video_id":      video_id,
            "video_url":     f"https://youtube.com/watch?v={video_id}",
            "thumbnail_url": meta["thumbnail"],
            "ai_summary":    content["summary"],
            "ai_outline":    content["outline"],
            "order_index":   data.order_index,
            "is_published":  True
        }).execute()

        module_id = module_result.data[0]["id"]
        logger.info(f"Module saved: ID {module_id}")
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to save module: {e}"
        )

    # Save transcript
    try:
        supabase.table("youtube_videos").upsert({
            "video_id":   video_id,
            "title":      meta["title"],
            "transcript": text_for_ai
        }).execute()
    except Exception as e:
        logger.error(f"Failed to save transcript: {e}")

    # Step 6: Embed for RAG
    logger.info("Embedding for RAG search...")
    chunks = split_text(text_for_ai)
    if len(chunks) > MAX_CHUNKS:
        chunks = chunks[:MAX_CHUNKS]

    try:
        embeddings = get_embeddings_batch(chunks)
        rows = [{
            "content":  chunk,
            "metadata": {
                "source":      f"https://youtube.com/watch?v={video_id}",
                "video_id":    video_id,
                "type":        "course_module",
                "module_id":   module_id,
                "topic":       data.topic,
                "source_type": source_type,
                "chunk_index": i
            },
            "embedding": embeddings[i]
        } for i, chunk in enumerate(chunks)]

        supabase.table("documents").insert(rows).execute()
        logger.info(f"Embedded {len(chunks)} chunks")
    except Exception as e:
        logger.error(f"Embedding failed: {e}")

    logger.info(f"=== Success: {meta['title']} ===")

    return {
        "message":         f"Course module created: {meta['title']}",
        "module_id":       module_id,
        "title":           meta["title"],
        "topic":           data.topic,
        "source_type":     source_type,
        "thumbnail":       meta["thumbnail"],
        "chunks_embedded": len(chunks)
    }


@app.post("/api/chat")
def chat_with_ai(data: ChatRequest):
    """Answers bar exam questions using RAG + AI"""

    # 1. Embed query
    try:
        query_vector = get_embeddings_batch([data.message])[0]
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Query embedding failed: {e}"
        )

    # 2. RAG search
    try:
        result = supabase.rpc("match_documents", {
            "query_embedding": query_vector,
            "match_threshold": RAG_THRESHOLD,
            "match_count":     RAG_MATCH_COUNT
        }).execute()
        context_chunks = [r["content"] for r in result.data]
    except Exception as e:
        logger.error(f"RAG search failed: {e}")
        context_chunks = []

    # 3. Build prompt
    context_text = sanitize_for_prompt(
        "\n---\n".join(context_chunks) if context_chunks
        else "No specific study material found."
    )

    system_prompt = f"""You are a professional encouraging Bar Exam prep coach
with deep knowledge of all MBE and MEE subjects including:
Constitutional Law, Contracts, Torts, Criminal Law, Civil Procedure,
Evidence, Real Property, Business Associations, Family Law, and Wills and Trusts.

Your role is to:
1. Answer bar exam questions accurately using your legal knowledge
2. Explain legal concepts step-by-step with clear legal reasoning
3. Reference relevant cases statutes and legal rules when applicable
4. Be encouraging and supportive to the student
5. If a student answers incorrectly explain why and give the correct answer

Do NOT include any promotional text advertisements or links.

=== STUDY MATERIAL CONTEXT ===
{context_text}"""

    # 4. Build messages
    messages = (
        [{"role": "system", "content": system_prompt}]
        + [{"role": m.role, "content": m.content} for m in data.history]
        + [{"role": "user", "content": data.message}]
    )

    # 5. Try Pollinations first
    try:
        res = requests.post(POLLINATIONS_URL, json={
            "messages": messages,
            "model":    "openai",
            "private":  True
        }, timeout=15)
        if res.status_code == 200 and res.text.strip():
            reply = clean_llm_response(res.text.strip())
            if reply:
                logger.info("Response via Pollinations")
                return {"reply": reply}
    except Exception as e:
        logger.warning(f"Pollinations failed: {e}")

    # 6. Groq fallback
    if groq_client:
        try:
            completion = groq_client.chat.completions.create(
                messages=messages,
                model=GROQ_MODEL,
                max_tokens=1024,
                temperature=0.7
            )
            reply = clean_llm_response(
                completion.choices[0].message.content.strip()
            )
            logger.info("Response via Groq")
            return {"reply": reply}
        except Exception as e:
            raise HTTPException(
                status_code=500,
                detail=f"Groq failed: {e}"
            )

    raise HTTPException(
        status_code=500,
        detail="All LLM services temporarily unavailable."
    )


@app.get("/api/affirmation")
def get_daily_affirmation():
    """Generates a daily bar exam affirmation"""
    try:
        res = requests.post(POLLINATIONS_URL, json={
            "messages": [
                {
                    "role":    "system",
                    "content": "You are an inspiring mentor to future lawyers. Do NOT include promotional text or links."
                },
                {
                    "role":    "user",
                    "content": "Give a short 2-3 sentence bar exam affirmation. Only the affirmation text nothing else."
                }
            ],
            "model": "openai"
        }, timeout=10)
        if res.status_code == 200 and res.text.strip():
            reply = clean_llm_response(res.text.strip())
            if reply:
                return {"affirmation": reply}
    except Exception as e:
        logger.error(f"Affirmation Pollinations failed: {e}")

    if groq_client:
        try:
            completion = groq_client.chat.completions.create(
                messages=[
                    {
                        "role":    "system",
                        "content": "You are an inspiring mentor to future lawyers."
                    },
                    {
                        "role":    "user",
                        "content": "Give a short 2-3 sentence encouraging bar exam affirmation."
                    }
                ],
                model=GROQ_MODEL,
                max_tokens=150,
                temperature=0.9
            )
            reply = completion.choices[0].message.content.strip()
            if reply:
                return {"affirmation": reply}
        except Exception as e:
            logger.error(f"Affirmation Groq failed: {e}")

    return {
        "affirmation": (
            "You have the analytical mind, the diligence, and the "
            "capability to conquer this exam. One rule, one analysis, "
            "and one day at a time."
        )
    }
